[package]
name = "silentpayments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bdk = {version = "0.20.0", features= ["all-keys"] }
secp256k1 = {version = "0.27", features = ["bitcoin-hashes-std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# rust-crypto = "0.2"
# sha2 = "0.10"
hex = "0.4"
bech32 = "0.9"
# bip32 = { version = "0.5", features = ["alloc"] }
